config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/destroy'
  get 'favorites/create'
  get 'books/index'
  root to: 'top#top'
  devise_for :users
  get 'posts/search' => 'posts#search'
  get 'posts/other_users_posts' => 'posts#other_posts'

  resources :posts
  resources :languages

  resources :users
  get 'practice' => 'timers#practice'
  resources :timers, only: %i[show new index create update]
end

app/models/timer.rb
# frozen_string_literal: true

class Timer < ApplicationRecord
  belongs_to :user
end

app/controllers/timers_controller.rb
# frozen_string_literal: true

class TimersController < ApplicationController
  before_action :timer_user, only: %i[show update]

  def index
    @timers = current_user.timers.all

    @hour_total = 0
    @min_total = 0
    @sec_total = 0

    @timers.each do |f|
      @hour_total += f.hour
    end

    @timers.each do |f|
      @min_total += f.min
      if @min_total > 59
        @min_total -= 60
        @hour_total += 1
      end
    end
    @timers.each do |f|
      @sec_total += f.sec
      if @sec_total > 59
        @sec_total -= 60
        @min_total += 1
      end
    end

    if params[:dt].nil?
      input_day = Date.today
      slice =   input_day.end_of_month.mday
      gon.alltime = Array.new(slice, 0)
      @first_page = '閲覧したい月を選んでください'
    else
      input_day = params[:dt]
      slice =   (params[:dt][8] + params[:dt][9]).to_i
      all_time = current_user.timers.where(created_at: input_day.in_time_zone.all_month)
      array_time = all_time.group('DAY(created_at)').sum(:total).to_a
      gon.alltime = Array.new(slice, 0)
      gon.start_day = params[:sdt]
      gon.end_day = params[:dt]
      @select_month = Date.parse(params[:dt]).strftime('%m')
    end

    if array_time.blank?
      @first_page ||= @no_date = @select_month + '月のデータはありません'
    else
      array_time.length.times do |f|
        day_total = array_time[f][0]
        gon.alltime[day_total - 1] = ((array_time[f][1]) / 3600.to_f).round(1)
      end
      @month_time = @select_month + '月の勉強時間:' + all_time.sum(:hour).to_s + '時間' + all_time.sum(:min).to_s + '分' + all_time.sum(:sec).to_s + '秒'
    end
  end

  def create
    timer = Timer.new(timer_params)
    timer.user_id = current_user.id
    timer.hour = params[:timer][:hour]
    hour = params[:timer][:hour].to_i * 3600

    timer.min = params[:timer][:min]
    min = params[:timer][:min].to_i * 60

    timer.sec = params[:timer][:sec]
    sec = params[:timer][:sec].to_i

    timer.detail = params[:timer][:detail]

    timer.total = hour + min + sec
    timer.save
    redirect_to timer_path(timer.id)
  end

  def new
    @timer = Timer.new
  end

  def show
    @timer = Timer.find(params[:id])
    @timers = current_user.timers.all

    @hour_total = 0
    @min_total = 0
    @sec_total = 0

    @timers.each do |f|
      @hour_total += f.hour
    end

    @timers.each do |f|
      @min_total += f.min
      if @min_total > 59
        @min_total -= 60
        @hour_total += 1
      end
    end
    @timers.each do |f|
      @sec_total += f.sec
      if @sec_total > 59
        @sec_total -= 60
        @min_total += 1
      end
    end
  end

  def update
    timer = Timer.find(params[:id])
    timer.hour = params[:timer][:hour]
    timer.min = params[:timer][:min]
    timer.sec = params[:timer][:sec]
    timer.detail = params[:timer][:detail]
    timer.save
    redirect_to timer_path(timer.id)
  end

  private

  def timer_params
    params.require(:timer).permit(timer: %i[hour min sec])
  end

  def timer_user
    timer = Timer.find(params[:id])
    if current_user.id != timer.user_id
      flash[:notice] = '不正な画面遷移です'
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/timers_helper.rb
# frozen_string_literal: true

module TimersHelper
end

app/views/timers/index.html.erb
<div class="month_select">
    <%= form_tag(timers_path, :method => "get") do  %>
        <%= select_tag(:month,options_for_select( [["1月", 1],["2月", 2],["3月", 3],["4月", 4],["5月", 5],["6月", 6],["7月", 7],["8月", 8],["9月", 9],["10月", 10],["11月", 11],["12月", 12]]), id:"month_search") %>
        <%= hidden_field_tag :sdt %>
        <%= hidden_field_tag :dt %>
        <%= submit_tag "送信", id:"month_submit"%>
    <% end %>
</div>

<div class="graph">
    <div class="month_total">
        <h4 style="text-align:center;"><%= @first_page %></h4>
        <h4 style="text-align:center;"><%= @month_time %></h4>
        <h4 style="text-align:center;">現在の総勉強時間: <%= @hour_total %>時間<%= @min_total %>分<%= @sec_total %>秒です</h4>
    </div>
    <canvas id="chartBox"></canvas>
    <%= link_to "手動で時間を入力したい場合はこちらへ", new_timer_path, class:"link_timer" %></li>
</div>


<script>
$(document).on("click", "#month_submit", function(){
    var month_num = $("#month_search").val();
    const year = 2019;

    var zmonth = (Number(month_num)-1);
    var start_day = new Date(year, zmonth);

    var month = (Number(month_num));
    var end_day = new Date(year, month, 0);

    $("#sdt").val(start_day);
    $("#dt").val(end_day);
})
        $(document).ready(function() {
            new Chart(document.getElementById("chartBox"), {
            type: 'bar',
            data: {
                datasets: [{
                    data: gon.alltime,
                    label: "",
                    borderWidth: 2,
                    borderColor: "#3e95cd",
                    fill: false,
                    pointRadius: 0
                }]
            },
            options: {
                scales: {
                    xAxes: [{
                    type: 'time',
                    time: {
                        parser: 'YYYY-MM-DD',
                        unit: "day",
                        displayFormats: {
                        day: 'M月D日'
                        },
                        min: gon.start_day,
                        max: gon.end_day
                    },
                    ticks: {
                        source: 'data'
                    },
                    title: {
                        display: true,
                        text: "１ヶ月の勉強時間"
                    }
                    }],
                    yAxes: [{
                        ticks: {
                            suggestedMax: 24,
                            suggestedMin: 0,
                            stepSize: 3
                        }
                    }]
                },
                legend: {
                    display: false
                },
                animation: {
                    duration: 10,
                },
                hover: {
                    animationDuration: 0,
                },
                responsiveAnimationDuration: 0
            },
            plugins: [{
                beforeInit: function(chart) {
                    var time = chart.options.scales.xAxes[0].time, // 'time' object reference
                    timeDiff = moment(time.max).diff(moment(time.min), 'd'); // difference (in days) between min and max date
                    for (i = 0; i <= timeDiff; i++) {
                        var _label = moment(time.min).add(i, 'd').format('YYYY-MM-DD HH:mm:ss');
                        chart.data.labels.push(_label);
                    }
                }
            }]
            });
        });
</script>


<style >
#month_submit {
    width: 60px;
    height: 30px;
}
#month_search{
    width: 70px;
    height: 30px;
}
.month_select{
    margin:20px;
    text-align:center;
}
.graph{
    width:700px;
    height:600px;
    margin:50px auto 0 auto;
}
.time-total{
    display:inline-block;
    margin:0 auto;
}
.month_total{
    margin: 30px auto;
    padding:20px;
    border: 1px solid black;
    width:450px;
}
.link_timer{
    margin: 0 0 40px 430px;
}
</style>

app/views/timers/new.html.erb
<br>
<div class="timer">
    <div class="border">
    <h3 class="put_time">時間を入力できます</h3><br><br>
    <%= form_for @timer, url:timers_path, method: :post do |d| %>
        <%= d.number_field :hour, max:24 %>時間<br><br>
        <%= d.number_field :min, max: 59 %>　分<br><br>
        <%= d.number_field :sec, max:59 %>　秒<br><br>
        <%= d.text_area :detail,:placeholder => "メモ記入欄" %><br><br>
        <%= d.submit %>
    <% end %>
<br>
    </div>
</div>

<style>
.timer{
    width: 400px;
    height:450px;
    border:2px groove grey;
    margin: 0 auto;
}
.border{
    margin-top:70px;
    text-align:center;
}
textarea{
    width:150px;
    height:40px;
    padding:10px 0 0 30px;
    margin-right:20px;
}
input[type="submit"]{
    -webkit-appearance: none;
    margin-right:17px;
    width:130px;
    padding:2px;
}

app/views/timers/practice.html.erb
<%= form_tag(practice_path, :method => "get") do  %>
    <%= select_tag(:month,options_for_select( [["1m", 1],["2m", 2],["3m", 3],["4m", 4],["5m", 5],["6m", 6],["7m", 7],["8m", 8],["9m", 9],["10m", 10],["11m", 11],["12m", 12]]), id:"month_search") %>

    <%= hidden_field_tag :sdt %>
    <%= hidden_field_tag :dt %>

    <%= submit_tag "送信", id:"month_submit"%>
<% end %>
<div class="graph">
    <canvas id="chartBox"></canvas>
</div>

<script>
$(document).on("click", "#month_submit", function(){
    var month_num = $("#month_search").val();
    const year = 2019;

    var zmonth = (Number(month_num)-1);
    var start_day = new Date(year, zmonth);

    var month = (Number(month_num));
    var end_day = new Date(year, month, 0);
            console.log(start_day);

    $("#sdt").val(start_day);
    $("#dt").val(end_day);
})

        $(document).ready(function() {
            new Chart(document.getElementById("chartBox"), {
            type: 'bar',
            data: {
                datasets: [{
                    data: gon.alltime,
                    label: "",
                    borderWidth: 2,
                    borderColor: "#3e95cd",
                    fill: false,
                    pointRadius: 0
                }]
            },
            options: {
                scales: {
                    xAxes: [{
                    type: 'time',
                    time: {
                        parser: 'YYYY-MM-DD',
                        unit: "day",
                        displayFormats: {
                        day: 'M月D日'
                        },
                        min: gon.start_day,
                        max: gon.end_day
                    },
                    ticks: {
                        source: 'data'
                    }
                    }]
                },
                legend: {
                    display: false
                },
                animation: {
                    duration: 0,
                },
                hover: {
                    animationDuration: 0,
                },
                responsiveAnimationDuration: 0
            },
            plugins: [{
                beforeInit: function(chart) {
                    var time = chart.options.scales.xAxes[0].time, // 'time' object reference
                    timeDiff = moment(time.max).diff(moment(time.min), 'd'); // difference (in days) between min and max date
                    for (i = 0; i <= timeDiff; i++) {
                        var _label = moment(time.min).add(i, 'd').format('YYYY-MM-DD HH:mm:ss');
                        chart.data.labels.push(_label);
                    }
                }
            }]
            });
        });



</script>


<style >
.month_select{
    margin:20px;
    text-align:center;
}
.graph{
    width:700px;
    height:600px;
    margin:50px auto;
}
.time-total{
    display:inline-block;
    margin:0 auto;
}
</style>

app/views/timers/show.html.erb
<div class="timer">
    <br>
    <p>お疲れ様です！</p>
    <h4><%= @timer.hour %>時間<%= @timer.min %>分<%= @timer.sec %>秒勉強しました。</h4><br>

    <p>こちらで修正できます。</p><br>
    <%= form_for @timer, url:timer_path(@timer.id), method: :patch do |d| %>
        <%= d.number_field :hour, max:24 %>時間<br><br>
        <%= d.number_field :min, max: 59 %>　分<br><br>
        <%= d.number_field :sec, max:59 %>　秒<br><br>
        <%= d.text_area :detail,:placeholder => "メモ記入欄" %><br><br>
        <%= d.submit %>
    <% end %>
<br>
    合計<%= @hour_total %>時間
    <%= @min_total %>分
    <%= @sec_total %>秒勉強しています
</div>

<style>
.timer{
    text-align:center;
}
textarea{
    width:170px;
    height:40px;
    padding:10px 0 0 45px;
}