config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/destroy'
  get 'favorites/create'
  get 'books/index'
  root to: 'top#top'
  devise_for :users
  get 'posts/search' => 'posts#search'
  get 'posts/other_users_posts' => 'posts#other_posts'

  resources :posts
  resources :languages

  resources :users
  get 'practice' => 'timers#practice'
  resources :timers, only: %i[show new index create update]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :language

  has_many_attached :images

  has_many :favorites
  validates :title, presence: true
  validates :body, presence: true
  validates :language_id, presence: true
  validates :user_id, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :post_user, except: %i[index show new update create search other_posts]

  def index
    @posts = current_user.posts.page(params[:page]).reverse_order
    @search = current_user.posts.ransack(params[:q])
    @lang = Language.all
    unless params[:q].nil?
      @search_search = current_user.posts.ransack(params[:q])
      @lang = Language.all
      @search = current_user.posts.search(search_params)
      @posts = (@search.result(distinct: true)).page(params[:page]).reverse_order
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  def update
    post = Post.find(params[:id])
    if params[:post][:check].nil?
    else
      params[:post][:check].each do |image_id|
        image = post.images.find(image_id)
        image.purge
      end
    end
    post.update(post_params)
    redirect_to post_path(post)
  end

  def other_posts
    @posts = Post.page(params[:page]).reverse_order
    @search = Post.ransack(params[:q])
    @lang = Language.all
    unless params[:q].nil?
      @search_search = current_user.posts.ransack(params[:q])
      @lang = Language.all
      @search = current_user.posts.search(search_params)
      @inu = @search.result(distinct: true)
      @posts = @inu.page(params[:page]).reverse_order
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :language_id, :title, :body, images: [])
  end

  def post_user
    post = Post.find(params[:id])
    if current_user.id != post.user_id
      flash[:notice] = '不正な画面遷移です'
      redirect_to user_path(current_user.id)
    end
  end

  def search_params
    params.require(:q).permit(:title_cont, :body_cont, :language_id_eq, :created_at_gteq, :created_at_lteq)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/edit.html.erb
<div class="edit">
    <%= form_with model: @post do |m| %>
        <p><%= m.text_field :title %></p>

        <p><%= m.text_area :body,rows:20, cols:40 %></p>

        <p><%= m.collection_select :language_id, Language.all, :id, :lang_name %></p>

        <p><%= m.file_field :images, multiple: true %></p>
    <p>削除したい画像にチェックしてください</p>
        <% @post.images.each do |image| %>
            <%= m.check_box :check, {:multiple => true}, image.id, false %>
            <%= image_tag image, :size=>"100x100" %> <br>
        <% end %>

        <p><%= m.submit %></p>
    <% end %>
</div>

<style>
.edit{
    text-align:center;
}
#post_images{
    display:inline-block;
}
</style>

app/views/posts/index.html.erb
<div class="search">
    <div class="glyphicon glyphicon-remove", id="remove"></div>
    <%= search_form_for(@search,url:posts_path) do |f|%>
        <p><%= f.collection_select :language_id_eq, @lang, :id, :lang_name, :include_blank => "言語選択" %></p><br>
        <p><%= f.text_field :title_cont, :placeholder => "タイトル" %></p><br>
	<p><%= f.text_area :body_cont, :placeholder => "本文" %></p><br>
        <p><%= f.text_field :created_at_gteq, :placeholder => "ex.09/01" %>~<%= f.text_field :created_at_lteq, :placeholder => "ex.09/05" %></p><br>
        <%= f.submit "検索", id:"search_submit"  %><br><br>
    <% end %>
</div>


<a href= "#" class="glyphicon glyphicon-search" id="custom_search">カスタム検索</a>

    <div id="other_user">
        <%= link_to "みんなの投稿はこちら" ,posts_other_users_posts_path %>
    </div>

<div class="post_all">

    <% if @posts == [] %>
        <br><br><h1 class="no_post" style="text-align:center;">
            投稿はありません
        </h1>
    <% else %>
        <% @posts.each do |post| %>
            <div class="post_each">
                <div class="post_top">
                    <div class="post_when"><%= post.updated_at %></div>
                    <div class="post_lang"><%= post.language.lang_name %></div> <br>
                </div>

                <div class="post_bottom">
                    <div class="post_title">
                    <%= link_to post_path(post.id) do%>
                        <%= post.title %>
                    <% end %>
                    </div>
                </div>
            </div>
        <% end %>
        <div class="paginate"><%= paginate @posts, class:"paginate" %></div>
    </div>
    <% end %>

<style>
/* search */
.search{
    margin-top:30px;
    width:100%;
    text-align:center;
}
.post_all{
    margin-top: 20px;
}
.post_each{
    margin: 0 auto;
    width:700px;
    height:70px;
    margin-bottom: 40px;
    border:solid 1px black;

}
.post_lang{
    float:left;
    font-size:20px;
    padding-left:15px;

}
.post_when{
    float:right;
    margin-left:30px;
}

.post_title{
    float:left;
    padding-left:20px;
    font-size:24px;

}
#other_user{
    font-size:19px;
    margin-top:20px;
    margin-left:64%;
}
.post_top{
    background-color: skyblue;
    height:30px;
    border-bottom:solid 1px black;
}
.post_bottom{
    width:100%;

}
.paginate{
    text-align:center;
    font-size: 20px;
}
.search {
    display:none;
}
#custom_search{
    font-size: 20px;
    left:64%;
    margin-top:50px;
    display: inline-block;
    border: 2px solid grey;
    padding:15px;
    border-radius: 50%;
}
input[type="text"]{
    width: 300px;
    height: 50px;
}
textarea{
    width:300px;
    height: 80px;
}
.search{
    margin-top:50px;
}
#remove{
    color:grey;
    font-size:30px;
    left:30%;
}
#search_submit {
   height:50px;
   width:90px;
}
</style>

<script>

$(document).on('click', "#custom_search", function(){
    $("#custom_search").fadeToggle();
    $('.post_all').fadeToggle();
    $(".search").slideToggle();
    return false;
});

$("#remove").on("click",function(){
    $("#custom_search").slideToggle();
    $('.post_all').slideToggle();
    $(".search").fadeToggle();
    return false;
});
</script>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
    <div id="error_explanation">

    <h2><%= @post.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
        <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
    </div>
<% end %>
<div class="page_all">
    <div class="post_form">
        <div class="margin">
            <%= form_for @post do |m| %>

                <p>タイトル:　<%= m.text_field :title %></p><br>

                <p>内容:　　　　<%= m.text_area :body %></p><br>

                <p>言語名:<%= m.collection_select :language_id, Language.all, :id, :lang_name %></p><br>

                <p><%= m.file_field :images, multiple: true %></p>

                <p><%= m.submit %></p>
            <% end %>
        </div>
    </div>
    <div class="mark_ex">
            <div class="title_ex">見やすい投稿の作り方</div><br>
        <div class="one_content">
            <div class="mark_content"># 見出し1</div>
            <div class="midashi1"">見出し１</div>
        </div>
        <div class="one_content">
            <div class="mark_content">## 見出し2</div>
            <div class="midashi2">見出し２</div>
        </div>
        <div class="one_content">
            <div class="mark_content">~取り消し線~</div>
            <div class="torikeshi">取り消し線</div>
        </div>
        <div class="one_content">
            <div class="mark_content">```文章をバッククォーテーション３つで囲む```</div>
            <div class="border">文章が枠線で囲まれます</div>
        </div>
        <div class="one_content">
            <div class="mark_content">`文章をバッククォーテーション1つで囲む`</div>
            <div class="border_red">文章が強調表示されます</div>
        </div>
        <div class="one_content">
            <div class="mark_content">*アスタリスク1つで囲む*</div>
            <div class="italic">文字が斜めになります</div>
        </div>
        <div class="one_content">
            <div class="mark_content">***アスタリスク３つで囲む***</div>
            <div class="bold">文字が濃くなります</div>
        </div>
        <div class="one_content">
            <div class="mark_content">***アスタリスク３つ記述すると水平線が引けます</div>
            <div class="line"></div>
        </div>
    </div>
</div>

<style>
.error_explanation{
    margin-bottom:30px;
}
.page_all{
    margin:50px 5% 0 10%;
}
.post_form {
    border-right:2px solid grey;
    height:600px;
    margin:30px 0 0 0;
    padding-right:5%;
    float:left;
}
#post_title{
    width:400px;

}
#post_body{
    width:400px;
    height:400px;
}
.margin{
    text-align: center;
}
input[type="file"]{
    display: inline-block;
}
.mark_ex{
    padding-left: 90px;
    width: 500px;
    text-align:center;
    margin:0 auto;
    display: inline-block;
    font-size:18px;
}
.title_ex{
    margin-top:10px;
    padding:3px;
    font-size:23px;
    font-weight:bold;
    border:2px solid white;
    background-color:skyblue;
}
.mark_content{
    margin-bottom:8px;
}
.one_content{
    margin-bottom: 20px;
}
.midashi1{
    font-size:27px;
    font-weight:bold;
}
.midashi2{
    font-size:22px;
    font-weight:bold;
}
.torikeshi{
    text-decoration:line-through;
}
.border{
    background-color: #dcdcdc;
    border:1px solid black;
    width:200px;
    margin: 0 auto;
}
.border_red{
    margin: 0 auto;
    color: #c7254e;
    background-color:#f9f2f4;
    width:200px;
}
.italic{
    font-style:italic;
}
.bold {
    font-weight:bold;
}
.line{
    border-top:1px solid grey;
}



</style>

<script>

</script>

app/views/posts/other_posts.html.erb
<div class="search">
    <div class="glyphicon glyphicon-remove", id="remove"></div>

    <%= search_form_for(@search,url:posts_other_users_posts_path) do |f|%>
        <p><%= f.collection_select :language_id_eq, @lang, :id, :lang_name, :include_blank => "言語選択" %></p><br>
        <p><%= f.text_field :title_cont, :placeholder => "タイトル" %></p><br>
        <p><%= f.text_area :body_cont, :placeholder => "本文" %></p><br>
        <p><%= f.text_field :created_at_gteq, :placeholder => "ex.09/01" %>~<%= f.text_field :created_at_lteq, :placeholder => "ex.09/05" %></p><br>
        <%= f.submit "検索", id:"search_submit"  %><br><br>
    <% end %>
</div>

<h2 class="page_title">＜ みんなの投稿 ＞</h2>

<a href= "#" class="glyphicon glyphicon-search" id="custom_search">カスタム検索</a>

<div class="post_all">
    <% @posts.each do |post| %>
        <div class="post_each">
        <div class="post_left">
            <% if post.user.image.attached? %>
                <p><%= image_tag post.user.image, size:"70x70" %></p>
            <% else %>
                <p><%= image_tag "no_image.png", size:"70x70" %></p>
            <% end %>
        </div>
            <div class="post_top">
                <div class="post_when"><%= post.updated_at %></div>
                <div class="post_when"><%= post.user.name %></div>
                <div class="post_lang"><%= post.language.lang_name %></div> <br>
            </div>

            <div class="post_bottom">
                <div class="post_title">
                <%= link_to post_path(post.id) do%>
                    <%= post.title %>
                <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <div class="paginate"><%= paginate @posts, class:"paginate" %></div>
</div>

</div>
<style>
/* search */
.search{
    margin-top:10px;
    width:100%;
    text-align:center;
}
.post_all{
    margin-top: 20px;
}
.post_each{
    margin: 0 auto;
    width:700px;
    height:70px;
    margin-bottom: 40px;
    border:solid 1px black;

}
.post_lang{
    float:left;
    font-size:20px;
    padding-left:15px;

}
.page_title{
margin-left:540px;
}
.post_when{
    float:right;
    margin-left:30px;
    font-size:15px;
}
.post_left{
    float:left;
    height:69px;
    border-right:1px solid black;
}
.post_left img{
    height:67.5px;
}
.post_title{
    float:left;
    padding-left:20px;
    font-size:24px;

}

.post_top{
    background-color: #FAAC58;
    height:30px;
    border-bottom:solid 1px black;
}
.post_bottom{
    width:100%;

}
.paginate{
    text-align:center;
    font-size: 20px;
}
.search {
    display:none;
}
#custom_search{
    font-size: 20px;
    left:64%;
    margin-top:25px;
    display: inline-block;
    border: 2px solid grey;
    padding:15px;
    border-radius: 50%;
}
input[type="text"]{
    width: 300px;
    height: 50px;
}
textarea{
    width:300px;
    height: 80px;
}
.search{
    margin-top:50px;
}
#remove{
    color:grey;
    font-size:30px;
    left:30%;
}
#search_submit {
   height:50px;
   width:90px;
}
</style>

<script>

$(document).on('click', "#custom_search", function(){
    $("#custom_search").fadeToggle();
    $('.post_all').fadeToggle();
    $('.page_title').fadeToggle();
    $(".search").slideToggle();
    return false;
});

$("#remove").on("click",function(){
    $("#custom_search").slideToggle();
    $('.post_all').slideToggle();
    $('.page_title').slideToggle();
    $(".search").fadeToggle();
    return false;
});
</script>

app/views/posts/show.html.erb
<div class="show_all">
    <div class="user_name">ユーザ名：<%= @post.user.name %></div>
    <div class="created_at">最終更新日:<%= @post.updated_at %></div>

    <div class="lang_name">言語名：<%= @post.language.lang_name %></div>

    <div class="post_title"><%= markdown(@post.title) %></div>


        <% if @post.images.attached? %>
            <% @post.images.each do |image| %>
                <p><%= image_tag image, size:"200x200" %></p>
            <% end %>
        <% end %>
    <div class="post_body">
        <p><%= markdown(@post.body).html_safe  %></p>
    </div>

    <%= link_to "一覧に戻る", posts_path %>
    <% if @post.user_id == current_user.id %>
        | <%= link_to "編集する", edit_post_path %> | <%= link_to "投稿の削除", post_path(@post), method: :delete, data: {confirm: "投稿を削除しますか？"} %> 
    <% end %>
</div>



<style>

.show_all{
    width:1024px;
    
    margin: 30px auto;
}
.post_body{
    
}
.post_title{
    
}
.lang_name{
    width:150px;
    border: solid 1px #dcdcdc;
    background-color: #dcdcdc;
}