config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/destroy'
  get 'favorites/create'
  get 'books/index'
  root to: 'top#top'
  devise_for :users
  get 'posts/search' => 'posts#search'
  get 'posts/other_users_posts' => 'posts#other_posts'

  resources :posts
  resources :languages

  resources :users
  get 'practice' => 'timers#practice'
  resources :timers, only: %i[show new index create update]
end

app/models/aaaaa.rb
i = gets.to_i * gets.to_i *  gets.to_i

p i

app/models/aafasdf.rb
str = gets

array = (str.chars).to_a
array.pop
length = array.length

length.times do |f|
    if array[f] == "A"
        array[f] = 4
    elsif array[f] == "E"
        array[f] = 3
    elsif array[f] == "G"
        array[f] = 6
    elsif array[f] == "I"
        array[f] = 1
    elsif array[f] == "0"
        array[f] = 0
    elsif array[f] == "S"
        array[f] = 5
    elsif array[f] == "Z"
        array[f] = 2
    end
end

result =  array.join

p result

app/models/ads.rb
str = gets.to_s

array = str.chars
array.pop
p array

length = array.length
p length
(length -1).times do |f|
    if array[f] = "A"
        array[f] = 4
    elsif array[f] = "E"
        array[f] = 3
    elsif array[f] = "G"
        array[f] = 6
    elsif array[f] = "I"
        array[f] = 1
    elsif array[f] = "0"
        array[f] = 0
    elsif array[f] = "S"
        array[f] = 5
    elsif array[f] = "Z"
        array[f] = 2
    end
end

result = array.join

p result

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user, dependent: :destroy
	belongs_to :post,dependent: :destroy
end

app/models/jiij.rb
loops = gets.to_i

loops.times do |f|
	"num" +((f).to_s) = gets.to_i
end

app/models/language.rb
# frozen_string_literal: true

class Language < ApplicationRecord
  has_many :posts
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :language

  has_many_attached :images

  has_many :favorites
  validates :title, presence: true
  validates :body, presence: true
  validates :language_id, presence: true
  validates :user_id, presence: true
end

app/models/timer.rb
# frozen_string_literal: true

class Timer < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy

  has_one_attached :image

  has_many :timers, dependent: :destroy

  has_many :favorites
end

app/models/uuu.rb
str = gets

array = (str.chars).to_a
array.pop
length = array.length

length.times do |f|
    if array[f] == "A"
        array[f] = 4
    elsif array[f] == "E"
        array[f] = 3
    elsif array[f] == "G"
        array[f] = 6
    elsif array[f] == "I"
        array[f] = 1
    elsif array[f] == "0"
        array[f] = 0
    elsif array[f] == "S"
        array[f] = 5
    elsif array[f] == "Z"
        array[f] = 2
    end
end

result = array.join
puts result

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  before_action :authenticate_user!, except: [:top]

  def top; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/languages_helper.rb
# frozen_string_literal: true

module LanguagesHelper
end

app/helpers/markdown_helper.rb
# frozen_string_literal: true

module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        filter_html: false,
        autolink: true,
        space_after_headers: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        tables: true,
        hard_wrap: false,
        xhtml: true,
        lax_html_blocks: true,
        strikethrough: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, options)
    end

    @markdown.render(text).html_safe
  end
  end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/timers_helper.rb
# frozen_string_literal: true

module TimersHelper
end

app/helpers/top_helper.rb
# frozen_string_literal: true

module TopHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProstaSoturon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <div class="container">
        <div class="nav navbar-nav navbar-left">
        <h4 class="header_greet">こんにちは<%= @header %>さん</h4>
      </div>

        <nav class="nav navbar-nav navbar-right">
          <ul>
            <% if user_signed_in? %>
                  <li><%= link_to "ユーザ詳細画面へ", user_path(current_user.id),class:'glyphicon glyphicon-user'%></li>
                  <li><%= link_to "投稿する", new_post_path,class:'glyphicon glyphicon-book' %></li>
                  <li><%= link_to "投稿一覧", posts_path,class:'glyphicon glyphicon-pencil' %></li>
                  <li><%= link_to "グラフ", timers_path,class:'glyphicon glyphicon-stats' %></li>
            <% else %>
                  <li><%= link_to "ログイン画面", new_user_session_path,class:'glyphicon glyphicon-user' %></li>
                  <li><%= link_to "会員登録画面", new_user_registration_path,class:'glyphicon glyphicon-user' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

  .navbar-right li {
    padding-top: 15px;
    margin:0 0 20px 20px;
    float: left;
    list-style: none;
  }

.header_greet {
  margin-left: 10px;
}
.glyphicon {
  color: black;
  font-size: 20px;
  font-weight: 100;
}


</style>
<script src="https://cdn.jsdelivr.net/npm/moment@latest/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>


    <%= yield %>
  </body>
</html>